package financialportal;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Christian Kasel
 */
public class FinancialPortalFrameView extends javax.swing.JFrame {

    private static ArrayList<JButton> buttons;

    /**
     * Creates new form PortalFrame
     */
    public FinancialPortalFrameView() {
        initComponents();
        buttons = new ArrayList<>();
        buttons.add(accountsPageTitleButton);
        buttons.add(budgetsPageTitleButton);
        buttons.add(loansPageTitleButton);
        buttons.add(spendingsPageTitleButton);
        buttons.add(transactionsPageTitleButton);
        buttons.add(trendsPageTitleButton);
    }

    /**
     * Function to select the page the user selected
     *
     * @param pageIndex the index of the page the user selected
     */
    public void enablePage(int pageIndex) {
        tabbedPane.setSelectedIndex(pageIndex);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        homePagePanel = new javax.swing.JPanel();
        homePageTitle = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        homePageTextArea = new javax.swing.JTextArea();
        accountsPagePanel = new javax.swing.JPanel();
        accountsPageTitlePanel = new javax.swing.JPanel();
        accountsPagePanelTitle = new javax.swing.JLabel();
        accountsPageTitleButton = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        accountsPageTable = new javax.swing.JTable();
        budgetsPagePanel = new javax.swing.JPanel();
        budgetsPageTitlePanel = new javax.swing.JPanel();
        budgetsPageTitle = new javax.swing.JLabel();
        budgetsPageTitleButton = new javax.swing.JButton();
        budgetsPageGraphPanel = new javax.swing.JPanel();
        loansPagePanel = new javax.swing.JPanel();
        loansPageTitlePanel = new javax.swing.JPanel();
        loansPageTitle = new javax.swing.JLabel();
        loansPageTitleButton = new javax.swing.JButton();
        loansPageTablePanel = new javax.swing.JPanel();
        spendingsPagePanel = new javax.swing.JPanel();
        spendingsPageTitlePanel = new javax.swing.JPanel();
        spendingsPageTitle = new javax.swing.JLabel();
        spendingsPageTitleButton = new javax.swing.JButton();
        spendingsPageTablePanel = new javax.swing.JPanel();
        transactionsPagePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        transactionsTable = new javax.swing.JTable();
        transactionsPageTitlePanel = new javax.swing.JPanel();
        transactionsPageTitle = new javax.swing.JLabel();
        transactionsPageTitleButton = new javax.swing.JButton();
        trendsPagePanel = new javax.swing.JPanel();
        trendsPageTitlePanel = new javax.swing.JPanel();
        trendsPageTitle = new javax.swing.JLabel();
        trendsPageTitleButton = new javax.swing.JButton();
        trendsPageTablePanel = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        fileButton = new javax.swing.JMenu();
        quitButton = new javax.swing.JMenuItem();
        pagesButton = new javax.swing.JMenu();
        homePageButton = new javax.swing.JMenuItem();
        accountsPageButton = new javax.swing.JMenuItem();
        budgetsPageButton = new javax.swing.JMenuItem();
        loansPageButton = new javax.swing.JMenuItem();
        spendingsPageButton = new javax.swing.JMenuItem();
        transactionsPageButton = new javax.swing.JMenuItem();
        trendsPageButton = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 625));
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 625));
        getContentPane().setLayout(new java.awt.CardLayout());

        tabbedPane.setPreferredSize(new java.awt.Dimension(1200, 645));
        tabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabbedPaneStateChanged(evt);
            }
        });

        homePagePanel.setLayout(new java.awt.BorderLayout());

        homePageTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homePageTitle.setText("Home Page");
        homePagePanel.add(homePageTitle, java.awt.BorderLayout.PAGE_START);

        homePageTextArea.setEditable(false);
        homePageTextArea.setColumns(20);
        homePageTextArea.setLineWrap(true);
        homePageTextArea.setRows(5);
        homePageTextArea.setText("Hello and welcome to your personal financial portal! At the top of the page you can see a list of tabs, which all have your financial data displayed in a convenient way for you. This portal is meant to be a tool for you to use to make the most informed decisions financially that you can.");
        homePageTextArea.setWrapStyleWord(true);
        jScrollPane3.setViewportView(homePageTextArea);

        homePagePanel.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        tabbedPane.addTab("Home Page", homePagePanel);

        accountsPagePanel.setLayout(new java.awt.BorderLayout());

        accountsPagePanelTitle.setText("Accounts Page");
        accountsPageTitlePanel.add(accountsPagePanelTitle);

        accountsPageTitleButton.setText("Select Info");
        accountsPageTitleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountsPageTitleButtonActionPerformed(evt);
            }
        });
        accountsPageTitlePanel.add(accountsPageTitleButton);

        accountsPagePanel.add(accountsPageTitlePanel, java.awt.BorderLayout.PAGE_START);

        accountsPageTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Amount", "Institution", "Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane7.setViewportView(accountsPageTable);
        if (accountsPageTable.getColumnModel().getColumnCount() > 0) {
            accountsPageTable.getColumnModel().getColumn(0).setResizable(false);
            accountsPageTable.getColumnModel().getColumn(1).setResizable(false);
            accountsPageTable.getColumnModel().getColumn(2).setResizable(false);
        }

        accountsPagePanel.add(jScrollPane7, java.awt.BorderLayout.CENTER);

        tabbedPane.addTab("Accounts", accountsPagePanel);

        budgetsPagePanel.setLayout(new java.awt.BorderLayout());

        budgetsPageTitle.setText("Budgets Page");
        budgetsPageTitlePanel.add(budgetsPageTitle);

        budgetsPageTitleButton.setText("Select Info");
        budgetsPageTitleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                budgetsPageTitleButtonActionPerformed(evt);
            }
        });
        budgetsPageTitlePanel.add(budgetsPageTitleButton);

        budgetsPagePanel.add(budgetsPageTitlePanel, java.awt.BorderLayout.PAGE_START);
        budgetsPagePanel.add(budgetsPageGraphPanel, java.awt.BorderLayout.CENTER);

        tabbedPane.addTab("Budgets", budgetsPagePanel);

        loansPagePanel.setLayout(new java.awt.BorderLayout());

        loansPageTitle.setText("Loans Page");
        loansPageTitlePanel.add(loansPageTitle);

        loansPageTitleButton.setText("Select Info");
        loansPageTitleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loansPageTitleButtonActionPerformed(evt);
            }
        });
        loansPageTitlePanel.add(loansPageTitleButton);

        loansPagePanel.add(loansPageTitlePanel, java.awt.BorderLayout.PAGE_START);
        loansPagePanel.add(loansPageTablePanel, java.awt.BorderLayout.CENTER);

        tabbedPane.addTab("Loans", loansPagePanel);

        spendingsPagePanel.setLayout(new java.awt.BorderLayout());

        spendingsPageTitle.setText("Spendings Page");
        spendingsPageTitlePanel.add(spendingsPageTitle);

        spendingsPageTitleButton.setText("Select Info");
        spendingsPageTitleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spendingsPageTitleButtonActionPerformed(evt);
            }
        });
        spendingsPageTitlePanel.add(spendingsPageTitleButton);

        spendingsPagePanel.add(spendingsPageTitlePanel, java.awt.BorderLayout.PAGE_START);
        spendingsPagePanel.add(spendingsPageTablePanel, java.awt.BorderLayout.CENTER);

        tabbedPane.addTab("Spendings", spendingsPagePanel);

        transactionsPagePanel.setLayout(new java.awt.BorderLayout());

        transactionsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Amount", "Date", "Institution"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        transactionsTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(transactionsTable);
        if (transactionsTable.getColumnModel().getColumnCount() > 0) {
            transactionsTable.getColumnModel().getColumn(0).setResizable(false);
            transactionsTable.getColumnModel().getColumn(1).setResizable(false);
            transactionsTable.getColumnModel().getColumn(2).setResizable(false);
        }

        transactionsPagePanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        transactionsPageTitle.setText("Transactions Page");
        transactionsPageTitlePanel.add(transactionsPageTitle);

        transactionsPageTitleButton.setText("Select Info");
        transactionsPageTitleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionsPageTitleButtonActionPerformed(evt);
            }
        });
        transactionsPageTitlePanel.add(transactionsPageTitleButton);

        transactionsPagePanel.add(transactionsPageTitlePanel, java.awt.BorderLayout.PAGE_START);

        tabbedPane.addTab("Transactions", transactionsPagePanel);

        trendsPagePanel.setLayout(new java.awt.BorderLayout());

        trendsPageTitle.setText("Trends Page");
        trendsPageTitlePanel.add(trendsPageTitle);

        trendsPageTitleButton.setText("Select Info");
        trendsPageTitleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trendsPageTitleButtonActionPerformed(evt);
            }
        });
        trendsPageTitlePanel.add(trendsPageTitleButton);

        trendsPagePanel.add(trendsPageTitlePanel, java.awt.BorderLayout.PAGE_START);
        trendsPagePanel.add(trendsPageTablePanel, java.awt.BorderLayout.CENTER);

        tabbedPane.addTab("Trends", trendsPagePanel);

        getContentPane().add(tabbedPane, "card2");

        fileButton.setText("File");

        quitButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, 0));
        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });
        fileButton.add(quitButton);

        menuBar.add(fileButton);

        pagesButton.setText("Pages");

        homePageButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, 0));
        homePageButton.setText("Home");
        homePageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homePageButtonActionPerformed(evt);
            }
        });
        pagesButton.add(homePageButton);

        accountsPageButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, 0));
        accountsPageButton.setText("Accounts");
        accountsPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountsPageButtonActionPerformed(evt);
            }
        });
        pagesButton.add(accountsPageButton);

        budgetsPageButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, 0));
        budgetsPageButton.setText("Budgets");
        budgetsPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                budgetsPageButtonActionPerformed(evt);
            }
        });
        pagesButton.add(budgetsPageButton);

        loansPageButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, 0));
        loansPageButton.setText("Loans");
        loansPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loansPageButtonActionPerformed(evt);
            }
        });
        pagesButton.add(loansPageButton);

        spendingsPageButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, 0));
        spendingsPageButton.setText("Spending");
        spendingsPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spendingsPageButtonActionPerformed(evt);
            }
        });
        pagesButton.add(spendingsPageButton);

        transactionsPageButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, 0));
        transactionsPageButton.setText("Transactions");
        transactionsPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionsPageButtonActionPerformed(evt);
            }
        });
        pagesButton.add(transactionsPageButton);

        trendsPageButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_7, 0));
        trendsPageButton.setText("Trends");
        trendsPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trendsPageButtonActionPerformed(evt);
            }
        });
        pagesButton.add(trendsPageButton);

        menuBar.add(pagesButton);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homePageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homePageButtonActionPerformed
        enablePage(0);
    }//GEN-LAST:event_homePageButtonActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitButtonActionPerformed

    private void accountsPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountsPageButtonActionPerformed
        enablePage(1);
    }//GEN-LAST:event_accountsPageButtonActionPerformed

    private void budgetsPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_budgetsPageButtonActionPerformed
        enablePage(2);
    }//GEN-LAST:event_budgetsPageButtonActionPerformed

    private void loansPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loansPageButtonActionPerformed
        enablePage(3);
    }//GEN-LAST:event_loansPageButtonActionPerformed

    private void spendingsPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spendingsPageButtonActionPerformed
        enablePage(4);
    }//GEN-LAST:event_spendingsPageButtonActionPerformed

    private void transactionsPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionsPageButtonActionPerformed
        getInfo("frame of reference", "transactions");
        enablePage(5);
    }//GEN-LAST:event_transactionsPageButtonActionPerformed

    private void trendsPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trendsPageButtonActionPerformed
        enablePage(6);
    }//GEN-LAST:event_trendsPageButtonActionPerformed

    private void tabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabbedPaneStateChanged

    }//GEN-LAST:event_tabbedPaneStateChanged

    private void accountsPageTitleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountsPageTitleButtonActionPerformed
        setAccInst(getInfo("institution", "account"));
        setAccType(getInfo("type", "account"));
        if (!notHome) {
            notHome = true;
        }

    }//GEN-LAST:event_accountsPageTitleButtonActionPerformed

    private void budgetsPageTitleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_budgetsPageTitleButtonActionPerformed
        if (!notHome) {
            notHome = true;
        }
        setBudType(getInfo("type", "budget"));

        addBarGraph();
    }//GEN-LAST:event_budgetsPageTitleButtonActionPerformed

    private void loansPageTitleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loansPageTitleButtonActionPerformed
        if (!notHome) {
            notHome = true;
        }
        setLoanInst(getInfo("institution", "loans"));
        setLoanID(Integer.parseInt(getInfo("loan ID", "loans")));
    }//GEN-LAST:event_loansPageTitleButtonActionPerformed

    private void spendingsPageTitleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spendingsPageTitleButtonActionPerformed
        if (!notHome) {
            notHome = true;
        }
        setSpendType(getInfo("type", "spending"));
//        addLineGraph();
    }//GEN-LAST:event_spendingsPageTitleButtonActionPerformed

    private void transactionsPageTitleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionsPageTitleButtonActionPerformed
        if (!notHome) {
            notHome = true;
        }
        setTransType(getInfo("frame of reference", "transaction"));
    }//GEN-LAST:event_transactionsPageTitleButtonActionPerformed

    private void trendsPageTitleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trendsPageTitleButtonActionPerformed
        trendsPageTablePanel.removeAll();
        if (!notHome) {
            notHome = true;
        }
        setTrendFrame(getInfo("frame of reference", "trend"));
        setTrendType(getInfo("type", "trend"));
        addLineGraph();
    }//GEN-LAST:event_trendsPageTitleButtonActionPerformed

    public void addBarGraph() {
        ArrayList<Budget> budgets = new ArrayList<>();
        budgets.add(new Budget(600, "January 2020", 400, "Utilities"));
        budgets.add(new Budget(500, "January 2020", 350, "Car Bill"));
        budgets.add(new Budget(250, "January 2020", 75, "Food"));
        budgets.add(new Budget(200, "January 2020", 150, "Water Bill"));
        budgets.add(new Budget(400, "May 2020", 250, "Gas"));
        budgets.add(new Budget(600, "February 2020", 400, "Utilities"));
        budgets.add(new Budget(500, "February 2020", 350, "Car Bill"));
        budgets.add(new Budget(250, "February 2020", 75, "Food"));
        budgets.add(new Budget(200, "February 2020", 150, "Water Bill"));
        budgets.add(new Budget(400, "February 2020", 250, "Gas"));
        budgets.add(new Budget(600, "March 2020", 400, "Utilities"));
        budgets.add(new Budget(500, "March 2020", 350, "Car Bill"));
        budgets.add(new Budget(250, "March 2020", 75, "Food"));
        budgets.add(new Budget(200, "March 2020", 150, "Water Bill"));
        budgets.add(new Budget(400, "March 2020", 250, "Gas"));
        budgets.add(new Budget(600, "April 2020", 400, "Utilities"));
        budgets.add(new Budget(500, "April 2020", 350, "Car Bill"));
        budgets.add(new Budget(250, "April 2020", 75, "Food"));
        budgets.add(new Budget(200, "April 2020", 150, "Water Bill"));
        budgets.add(new Budget(400, "April 2020", 250, "Gas"));
        budgets.add(new Budget(600, "May 2020", 400, "Utilities"));
        budgets.add(new Budget(500, "May 2020", 350, "Car Bill"));
        budgets.add(new Budget(250, "May 2020", 75, "Food"));
        budgets.add(new Budget(200, "May 2020", 150, "Water Bill"));
        budgets.add(new Budget(400, "May 2020", 250, "Gas"));
        DefaultCategoryDataset data = new DefaultCategoryDataset();
        budgets.forEach((b) -> {
            data.addValue(b.getAmount(), b.getType(), b.getFrame());
        });
        JFreeChart chart = ChartFactory.createBarChart("Budgets Graph for " + budgets.get(0).getFrame(), "Type", "Amount", data);
        ChartPanel panel = new ChartPanel(chart);
        budgetsPageGraphPanel.add(panel);
    }

    public void addLineGraph() {
        ArrayList<Trend> trends = new ArrayList<>();
        trends.add(new Trend(100, "January 2020", "Food"));
        trends.add(new Trend(200, "January 2020", "Gas"));
        trends.add(new Trend(300, "January 2020", "Utilities"));
        trends.add(new Trend(400, "January 2020", "Grocery"));
        trends.add(new Trend(500, "January 2020", "Bills"));
        trends.add(new Trend(600, "January 2020", "Movies"));
        trends.add(new Trend(200, "May 2020", "Food"));
        trends.add(new Trend(300, "May 2020", "Gas"));
        trends.add(new Trend(400, "May 2020", "Utilities"));
        trends.add(new Trend(500, "May 2020", "Grocery"));
        trends.add(new Trend(600, "May 2020", "Bills"));
        trends.add(new Trend(700, "May 2020", "Movies"));
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        trends.forEach((t) -> {
            dataset.addValue(t.getAmount(), t.getType(), t.getFrame());
        });
        JFreeChart chart = ChartFactory.createLineChart("Trends Graph", "Frame", "Type", dataset);
        ChartPanel panel = new ChartPanel(chart);
        trendsPagePanel.add(panel);
        
//        String[] types = new String[5];
//        types[0] = "Utilities";
//        types[1] = "Car Bill";
//        types[2] = "Food";
//        types[3] = "Water Bill";
//        types[4] = "Gas";
//        String[] months = new String[12];
//        months[0] = "January";
//        months[1] = "February";
//        months[2] = "March";
//        months[3] = "April";
//        months[4] = "May";
//        months[5] = "June";
//        months[6] = "July";
//        months[7] = "August";
//        months[8] = "September";
//        months[9] = "October";
//        months[10] = "November";
//        months[11] = "December";
//        ArrayList<Spending> spendings = new ArrayList<>();
//        for (int i = 0; i < 5; i++) {
//            for (int j = 0; j < 12; j++) {
//                spendings.add(new Spending((10 * i) * 10, months[j], types[i]));
//            }
//        }
////        spendings.add(new Spending(600, "January", "Utilities"));
////        spendings.add(new Spending(500, "March", "Car Bill"));
////        spendings.add(new Spending(250, "May", "Food"));
////        spendings.add(new Spending(200, "July", "Water Bill"));
////        spendings.add(new Spending(400, "December", "Gas"));
//        LineChartSample chart = new LineChartSample(spendings);
//        ArrayList<Color> colors = new ArrayList<>();
//        colors.add(Color.red);
//        colors.add(Color.orange);
//        colors.add(Color.yellow);
//        colors.add(Color.green);
//        colors.add(Color.blue);
//        int j = 0;
//        for (int i = 0; i < spendings.size(); i++) {
//            Spending s = spendings.get(i);
//            if (i < 12) {
//                j = 0;
//            } else if (i >= 12 && i < 24) {
//                j = 1;
//            } else if (i >= 24 && i < 36) {
//                j = 2;
//            } else if (i >= 36 && i < 48) {
//                j = 3;
//            } else if (i >= 48 && i < 60) {
//                j = 4;
//            }
//            chart.addLine(colors.get(j), s);
//        }
//        spendingsPagePanel.add(chart);
//        chart.show();
    }

    public ArrayList<JButton> getButtons() {
        return buttons;
    }

    /**
     * Function to prompt the user to get the information they are seeking
     *
     * @param obj the type of object they want (frame of reference, type,
     * institution, etc.)
     * @param desInfo the type of that object they want (account, budget, loan,
     * etc.)
     * @return the string the user entered into the prompt
     */
    public String getInfo(String obj, String desInfo) {
        return JOptionPane.showInputDialog("Please enter the " + obj + " you seek for your " + desInfo + ":");
    }

    public boolean getNotHome() {
        return notHome;
    }

    public int getTabSelected() {
        return tabbedPane.getSelectedIndex();
    }

    public String getAccInst() {
        return accInst;
    }

    public String getAccType() {
        return accType;
    }

    public String getBudType() {
        return budType;
    }

    public int getLoanID() {
        return loanID;
    }

    public String getLoanInst() {
        return loanInst;
    }

    public String getSpendType() {
        return spendType;
    }

    public String getTransType() {
        return transType;
    }

    public String getTrendFrame() {
        return trendFrame;
    }

    public String getTrendType() {
        return trendType;
    }

    public void setAccInst(String accInst) {
        this.accInst = accInst;
    }

    public void setAccType(String accType) {
        this.accType = accType;
    }

    public void setBudType(String budType) {
        this.budType = budType;
    }

    public void setLoanID(int loanID) {
        this.loanID = loanID;
    }

    public void setLoanInst(String loanInst) {
        this.loanInst = loanInst;
    }

    public void setSpendType(String spendType) {
        this.spendType = spendType;
    }

    public void setTransType(String transType) {
        this.transType = transType;
    }

    public void setTrendFrame(String trendFrame) {
        this.trendFrame = trendFrame;
    }

    public void setTrendType(String trendType) {
        this.trendType = trendType;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinancialPortalFrameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinancialPortalFrameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinancialPortalFrameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinancialPortalFrameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FinancialPortalFrameView().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem accountsPageButton;
    private javax.swing.JPanel accountsPagePanel;
    private javax.swing.JLabel accountsPagePanelTitle;
    private javax.swing.JTable accountsPageTable;
    private javax.swing.JButton accountsPageTitleButton;
    private javax.swing.JPanel accountsPageTitlePanel;
    private javax.swing.JMenuItem budgetsPageButton;
    private javax.swing.JPanel budgetsPageGraphPanel;
    private javax.swing.JPanel budgetsPagePanel;
    private javax.swing.JLabel budgetsPageTitle;
    private javax.swing.JButton budgetsPageTitleButton;
    private javax.swing.JPanel budgetsPageTitlePanel;
    private javax.swing.JMenu fileButton;
    private javax.swing.JMenuItem homePageButton;
    private javax.swing.JPanel homePagePanel;
    private javax.swing.JTextArea homePageTextArea;
    private javax.swing.JLabel homePageTitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JMenuItem loansPageButton;
    private javax.swing.JPanel loansPagePanel;
    private javax.swing.JPanel loansPageTablePanel;
    private javax.swing.JLabel loansPageTitle;
    private javax.swing.JButton loansPageTitleButton;
    private javax.swing.JPanel loansPageTitlePanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu pagesButton;
    private javax.swing.JMenuItem quitButton;
    private javax.swing.JMenuItem spendingsPageButton;
    private javax.swing.JPanel spendingsPagePanel;
    private javax.swing.JPanel spendingsPageTablePanel;
    private javax.swing.JLabel spendingsPageTitle;
    private javax.swing.JButton spendingsPageTitleButton;
    private javax.swing.JPanel spendingsPageTitlePanel;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JMenuItem transactionsPageButton;
    private javax.swing.JPanel transactionsPagePanel;
    private javax.swing.JLabel transactionsPageTitle;
    private javax.swing.JButton transactionsPageTitleButton;
    private javax.swing.JPanel transactionsPageTitlePanel;
    private javax.swing.JTable transactionsTable;
    private javax.swing.JMenuItem trendsPageButton;
    private javax.swing.JPanel trendsPagePanel;
    private javax.swing.JPanel trendsPageTablePanel;
    private javax.swing.JLabel trendsPageTitle;
    private javax.swing.JButton trendsPageTitleButton;
    private javax.swing.JPanel trendsPageTitlePanel;
    // End of variables declaration//GEN-END:variables
    private String accInst;
    private String accType;
    private String budType;
    private String loanInst;
    private int loanID;
    private String spendType;
    private String transType;
    private String trendFrame;
    private String trendType;
    private boolean notHome = false;
}
