package financialportal;

import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.CategoryToPieDataset;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.PieDataset;
import org.jfree.util.TableOrder;

/**
 *
 * @author Christian Kasel
 */
public class FinancialPortalFrameView extends javax.swing.JFrame {

    private static ArrayList<JButton> buttons;

    /**
     * Creates new form PortalFrame
     */
    public FinancialPortalFrameView() {
        initComponents();
        buttons = new ArrayList<>();
        buttons.add(accountsPageTitleButton);
        buttons.add(budgetsPageTitleButton);
        buttons.add(loansPageTitleButton);
        buttons.add(spendingsPageTitleButton);
        buttons.add(transactionsPageTitleButton);
        buttons.add(trendsPageTitleButton);
    }

    /**
     * Function to select the page the user selected
     *
     * @param pageIndex the index of the page the user selected
     */
    public void enablePage(int pageIndex) {
        tabbedPane.setSelectedIndex(pageIndex);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        homePagePanel = new javax.swing.JPanel();
        homePageTitle = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        homePageTextArea = new javax.swing.JTextArea();
        accountsPagePanel = new javax.swing.JPanel();
        accountsPageTitlePanel = new javax.swing.JPanel();
        accountsPagePanelTitle = new javax.swing.JLabel();
        accountsPageTitleButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        budgetsPagePanel = new javax.swing.JPanel();
        budgetsPageTitlePanel = new javax.swing.JPanel();
        budgetsPageTitle = new javax.swing.JLabel();
        budgetsPageTitleButton = new javax.swing.JButton();
        budgetsPageComboBox = new javax.swing.JComboBox<>();
        budgetsPageGraphPanel = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        loansPagePanel = new javax.swing.JPanel();
        loansPageTitlePanel = new javax.swing.JPanel();
        loansPageTitle = new javax.swing.JLabel();
        loansPageTitleButton = new javax.swing.JButton();
        loansPageTablePanel = new javax.swing.JPanel();
        loanPageLoanInstitutionInfo = new javax.swing.JLabel();
        loanPageLoanAmountInfo = new javax.swing.JLabel();
        loanPageLoanInfo = new javax.swing.JLabel();
        loanPageLowPayment = new javax.swing.JLabel();
        loanPagePaymentSlider = new javax.swing.JSlider();
        loanPageHighPayment = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        spendingsPagePanel = new javax.swing.JPanel();
        spendingsPageTitlePanel = new javax.swing.JPanel();
        spendingsPageTitle = new javax.swing.JLabel();
        spendingsPageTitleButton = new javax.swing.JButton();
        spendingsPageGraphPanel = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        transactionsPagePanel = new javax.swing.JPanel();
        transactionsPageTitlePanel = new javax.swing.JPanel();
        transactionsPageTitle = new javax.swing.JLabel();
        transactionsPageTitleButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTextArea9 = new javax.swing.JTextArea();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTextArea10 = new javax.swing.JTextArea();
        trendsPagePanel = new javax.swing.JPanel();
        trendsPageTitlePanel = new javax.swing.JPanel();
        trendsPageTitle = new javax.swing.JLabel();
        trendsPageTitleButton = new javax.swing.JButton();
        trendsPageGraphPanel = new javax.swing.JPanel();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTextArea11 = new javax.swing.JTextArea();
        jScrollPane15 = new javax.swing.JScrollPane();
        jTextArea12 = new javax.swing.JTextArea();
        menuBar = new javax.swing.JMenuBar();
        fileButton = new javax.swing.JMenu();
        quitButton = new javax.swing.JMenuItem();
        pagesButton = new javax.swing.JMenu();
        homePageButton = new javax.swing.JMenuItem();
        accountsPageButton = new javax.swing.JMenuItem();
        budgetsPageButton = new javax.swing.JMenuItem();
        loansPageButton = new javax.swing.JMenuItem();
        spendingsPageButton = new javax.swing.JMenuItem();
        transactionsPageButton = new javax.swing.JMenuItem();
        trendsPageButton = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 625));
        getContentPane().setLayout(new java.awt.CardLayout());

        tabbedPane.setPreferredSize(new java.awt.Dimension(1200, 625));
        tabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabbedPaneStateChanged(evt);
            }
        });

        homePagePanel.setLayout(new java.awt.BorderLayout());

        homePageTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homePageTitle.setText("Home Page");
        homePagePanel.add(homePageTitle, java.awt.BorderLayout.PAGE_START);

        homePageTextArea.setEditable(false);
        homePageTextArea.setColumns(20);
        homePageTextArea.setLineWrap(true);
        homePageTextArea.setRows(5);
        homePageTextArea.setText("   Hello and welcome to your personal financial portal! At the top of the page you can see a list of tabs, which all have your financial data displayed in a convenient way for you. This portal is meant to be a tool for you to use to make the most informed decisions financially that you can.\n\n   Each tab has a button at the top for you to select the information you seek (institution, date, type, etc.). As of right now, it is expected of the user to know exactly what data they are looking for. The goal is to input all the data from the data source (a database for right now) and create a drop down list of all the information you seek to take away the need for the user to know exactly what they are looking for.\n\n   The pages and their functions are as follows:\n\n  - Accounts page: Centralized location for user's accounts (savings, checking, retirement, etc.)\n  - Budgets page: Display a user's payments and how much more they need to complete the payments\n  - Loans page: Display/interact with the user's loans/loan payoff plan\n  - Spendings page: Display the user's spendings (based on groups)\n  - Transactions page: Displays the user's transactions as a list\n  - Trends page: Displays groupings similar to the spendings over the span of time");
        homePageTextArea.setWrapStyleWord(true);
        homePageTextArea.setDragEnabled(false);
        homePageTextArea.setPreferredSize(new java.awt.Dimension(600, 625));
        jScrollPane3.setViewportView(homePageTextArea);

        homePagePanel.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        tabbedPane.addTab("Home Page", homePagePanel);

        accountsPagePanel.setLayout(new java.awt.BorderLayout());

        accountsPagePanelTitle.setText("Accounts Page");
        accountsPageTitlePanel.add(accountsPagePanelTitle);

        accountsPageTitleButton.setText("Select Info");
        accountsPageTitleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountsPageTitleButtonActionPerformed(evt);
            }
        });
        accountsPageTitlePanel.add(accountsPageTitleButton);

        accountsPagePanel.add(accountsPageTitlePanel, java.awt.BorderLayout.PAGE_START);

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 625));

        jScrollPane2.setPreferredSize(new java.awt.Dimension(350, 535));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Amount", "Institution", "Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setPreferredSize(new java.awt.Dimension(400, 625));
        jTable1.setSize(new java.awt.Dimension(400, 625));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel1.add(jScrollPane2);

        accountsPagePanel.add(jPanel1, java.awt.BorderLayout.CENTER);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(400, 625));

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("This is your accounts page! Go ahead and select the \"Select Info\" button and type in the data you wish to see! Displayed will be a list of all the accouts at the institution in which you requested.");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setDragEnabled(false);
        jTextArea1.setPreferredSize(new java.awt.Dimension(300, 500));
        jTextArea1.setSize(new java.awt.Dimension(300, 500));
        jScrollPane1.setViewportView(jTextArea1);

        accountsPagePanel.add(jScrollPane1, java.awt.BorderLayout.LINE_START);

        jScrollPane6.setPreferredSize(new java.awt.Dimension(400, 625));

        jTextArea3.setColumns(20);
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setText("This is your accounts page! Go ahead and select the \"Select Info\" button and type in the data you wish to see! Displayed will be a list of all the accouts at the institution in which you requested.");
        jTextArea3.setWrapStyleWord(true);
        jTextArea3.setPreferredSize(new java.awt.Dimension(300, 500));
        jTextArea3.setSize(new java.awt.Dimension(300, 500));
        jScrollPane6.setViewportView(jTextArea3);

        accountsPagePanel.add(jScrollPane6, java.awt.BorderLayout.LINE_END);

        tabbedPane.addTab("Accounts", accountsPagePanel);

        budgetsPagePanel.setLayout(new java.awt.BorderLayout());

        budgetsPageTitle.setText("Budgets Page");
        budgetsPageTitlePanel.add(budgetsPageTitle);

        budgetsPageTitleButton.setText("Load Data");
        budgetsPageTitleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                budgetsPageTitleButtonActionPerformed(evt);
            }
        });
        budgetsPageTitlePanel.add(budgetsPageTitleButton);

        budgetsPageComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                budgetsPageComboBoxActionPerformed(evt);
            }
        });
        budgetsPageTitlePanel.add(budgetsPageComboBox);

        budgetsPagePanel.add(budgetsPageTitlePanel, java.awt.BorderLayout.PAGE_START);

        budgetsPageGraphPanel.setPreferredSize(new java.awt.Dimension(280, 500));
        budgetsPageGraphPanel.setSize(new java.awt.Dimension(280, 500));
        budgetsPagePanel.add(budgetsPageGraphPanel, java.awt.BorderLayout.CENTER);

        jScrollPane7.setPreferredSize(new java.awt.Dimension(275, 500));
        jScrollPane7.setSize(new java.awt.Dimension(300, 500));

        jTextArea4.setEditable(false);
        jTextArea4.setColumns(20);
        jTextArea4.setLineWrap(true);
        jTextArea4.setRows(5);
        jTextArea4.setText("   Hello and welcome to your budgeting page! On this page you will see a type of budget, the total amout for the month and the amount left to be paid.\n\n   To load the data, please selec the \"Load Data\" button. Then a graph should appear with the first budget. The drop down menu should fill up with all of the budgets you can choose from. Just select the budget you wish to see, and the graph of that budget should appear in the middle section.");
        jTextArea4.setWrapStyleWord(true);
        jTextArea4.setPreferredSize(new java.awt.Dimension(300, 500));
        jTextArea4.setSize(new java.awt.Dimension(300, 500));
        jScrollPane7.setViewportView(jTextArea4);

        budgetsPagePanel.add(jScrollPane7, java.awt.BorderLayout.LINE_START);

        jScrollPane8.setPreferredSize(new java.awt.Dimension(275, 500));
        jScrollPane8.setSize(new java.awt.Dimension(300, 500));

        jTextArea5.setEditable(false);
        jTextArea5.setColumns(20);
        jTextArea5.setLineWrap(true);
        jTextArea5.setRows(5);
        jTextArea5.setText("   The red color represents how much of the monthly budget you have paid so far. The blue color represents how much of the budget you have left to pay off.\n\n   If only one color is shown, then either all or none of the budget needs to be paid for.");
        jTextArea5.setWrapStyleWord(true);
        jTextArea5.setPreferredSize(new java.awt.Dimension(275, 500));
        jTextArea5.setSize(new java.awt.Dimension(300, 500));
        jScrollPane8.setViewportView(jTextArea5);

        budgetsPagePanel.add(jScrollPane8, java.awt.BorderLayout.LINE_END);

        tabbedPane.addTab("Budgets", budgetsPagePanel);

        loansPagePanel.setLayout(new java.awt.BorderLayout());

        loansPageTitle.setText("Loans Page");
        loansPageTitlePanel.add(loansPageTitle);

        loansPageTitleButton.setText("Select Info");
        loansPageTitleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loansPageTitleButtonActionPerformed(evt);
            }
        });
        loansPageTitlePanel.add(loansPageTitleButton);

        loansPagePanel.add(loansPageTitlePanel, java.awt.BorderLayout.PAGE_START);

        loansPageTablePanel.setLayout(new java.awt.GridLayout(3, 3));

        loanPageLoanInstitutionInfo.setText("jLabel1");
        loansPageTablePanel.add(loanPageLoanInstitutionInfo);

        loanPageLoanAmountInfo.setText("jLabel2");
        loansPageTablePanel.add(loanPageLoanAmountInfo);

        loanPageLoanInfo.setText("jLabel6");
        loansPageTablePanel.add(loanPageLoanInfo);

        loanPageLowPayment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loanPageLowPayment.setText("0");
        loansPageTablePanel.add(loanPageLowPayment);

        loanPagePaymentSlider.setEnabled(false);
        loanPagePaymentSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                loanPagePaymentSliderStateChanged(evt);
            }
        });
        loansPageTablePanel.add(loanPagePaymentSlider);

        loanPageHighPayment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loanPageHighPayment.setText("-");
        loansPageTablePanel.add(loanPageHighPayment);

        jLabel8.setText("jLabel8");
        loansPageTablePanel.add(jLabel8);

        jLabel7.setText("jLabel7");
        loansPageTablePanel.add(jLabel7);

        jLabel4.setText("jLabel4");
        loansPageTablePanel.add(jLabel4);

        loansPagePanel.add(loansPageTablePanel, java.awt.BorderLayout.CENTER);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setWrapStyleWord(true);
        jScrollPane5.setViewportView(jTextArea2);

        loansPagePanel.add(jScrollPane5, java.awt.BorderLayout.LINE_START);

        tabbedPane.addTab("Loans", loansPagePanel);

        spendingsPagePanel.setLayout(new java.awt.BorderLayout());

        spendingsPageTitle.setText("Spendings Page");
        spendingsPageTitlePanel.add(spendingsPageTitle);

        spendingsPageTitleButton.setText("Select Info");
        spendingsPageTitleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spendingsPageTitleButtonActionPerformed(evt);
            }
        });
        spendingsPageTitlePanel.add(spendingsPageTitleButton);

        spendingsPagePanel.add(spendingsPageTitlePanel, java.awt.BorderLayout.PAGE_START);
        spendingsPagePanel.add(spendingsPageGraphPanel, java.awt.BorderLayout.CENTER);

        jTextArea7.setColumns(20);
        jTextArea7.setRows(5);
        jScrollPane10.setViewportView(jTextArea7);

        spendingsPagePanel.add(jScrollPane10, java.awt.BorderLayout.LINE_START);

        jTextArea8.setColumns(20);
        jTextArea8.setRows(5);
        jScrollPane11.setViewportView(jTextArea8);

        spendingsPagePanel.add(jScrollPane11, java.awt.BorderLayout.LINE_END);

        tabbedPane.addTab("Spendings", spendingsPagePanel);

        transactionsPagePanel.setLayout(new java.awt.BorderLayout());

        transactionsPageTitle.setText("Transactions Page");
        transactionsPageTitlePanel.add(transactionsPageTitle);

        transactionsPageTitleButton.setText("Select Info");
        transactionsPageTitleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionsPageTitleButtonActionPerformed(evt);
            }
        });
        transactionsPageTitlePanel.add(transactionsPageTitleButton);

        transactionsPagePanel.add(transactionsPageTitlePanel, java.awt.BorderLayout.PAGE_START);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Amount", "Date", "Institution"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel2.add(jScrollPane4);

        transactionsPagePanel.add(jPanel2, java.awt.BorderLayout.CENTER);

        jTextArea9.setColumns(20);
        jTextArea9.setRows(5);
        jScrollPane12.setViewportView(jTextArea9);

        transactionsPagePanel.add(jScrollPane12, java.awt.BorderLayout.LINE_START);

        jTextArea10.setColumns(20);
        jTextArea10.setRows(5);
        jScrollPane13.setViewportView(jTextArea10);

        transactionsPagePanel.add(jScrollPane13, java.awt.BorderLayout.LINE_END);

        tabbedPane.addTab("Transactions", transactionsPagePanel);

        trendsPagePanel.setLayout(new java.awt.BorderLayout());

        trendsPageTitle.setText("Trends Page");
        trendsPageTitlePanel.add(trendsPageTitle);

        trendsPageTitleButton.setText("Select Info");
        trendsPageTitleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trendsPageTitleButtonActionPerformed(evt);
            }
        });
        trendsPageTitlePanel.add(trendsPageTitleButton);

        trendsPagePanel.add(trendsPageTitlePanel, java.awt.BorderLayout.PAGE_START);
        trendsPagePanel.add(trendsPageGraphPanel, java.awt.BorderLayout.CENTER);

        jTextArea11.setColumns(20);
        jTextArea11.setRows(5);
        jScrollPane14.setViewportView(jTextArea11);

        trendsPagePanel.add(jScrollPane14, java.awt.BorderLayout.LINE_START);

        jTextArea12.setColumns(20);
        jTextArea12.setRows(5);
        jScrollPane15.setViewportView(jTextArea12);

        trendsPagePanel.add(jScrollPane15, java.awt.BorderLayout.LINE_END);

        tabbedPane.addTab("Trends", trendsPagePanel);

        getContentPane().add(tabbedPane, "card2");

        fileButton.setText("File");

        quitButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, 0));
        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });
        fileButton.add(quitButton);

        menuBar.add(fileButton);

        pagesButton.setText("Pages");

        homePageButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, 0));
        homePageButton.setText("Home");
        homePageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homePageButtonActionPerformed(evt);
            }
        });
        pagesButton.add(homePageButton);

        accountsPageButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, 0));
        accountsPageButton.setText("Accounts");
        accountsPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountsPageButtonActionPerformed(evt);
            }
        });
        pagesButton.add(accountsPageButton);

        budgetsPageButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, 0));
        budgetsPageButton.setText("Budgets");
        budgetsPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                budgetsPageButtonActionPerformed(evt);
            }
        });
        pagesButton.add(budgetsPageButton);

        loansPageButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, 0));
        loansPageButton.setText("Loans");
        loansPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loansPageButtonActionPerformed(evt);
            }
        });
        pagesButton.add(loansPageButton);

        spendingsPageButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, 0));
        spendingsPageButton.setText("Spending");
        spendingsPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spendingsPageButtonActionPerformed(evt);
            }
        });
        pagesButton.add(spendingsPageButton);

        transactionsPageButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, 0));
        transactionsPageButton.setText("Transactions");
        transactionsPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionsPageButtonActionPerformed(evt);
            }
        });
        pagesButton.add(transactionsPageButton);

        trendsPageButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_7, 0));
        trendsPageButton.setText("Trends");
        trendsPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trendsPageButtonActionPerformed(evt);
            }
        });
        pagesButton.add(trendsPageButton);

        menuBar.add(pagesButton);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homePageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homePageButtonActionPerformed
        enablePage(0);
    }//GEN-LAST:event_homePageButtonActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitButtonActionPerformed

    private void accountsPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountsPageButtonActionPerformed
        enablePage(1);
    }//GEN-LAST:event_accountsPageButtonActionPerformed

    private void budgetsPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_budgetsPageButtonActionPerformed
        enablePage(2);
    }//GEN-LAST:event_budgetsPageButtonActionPerformed

    private void loansPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loansPageButtonActionPerformed
        enablePage(3);
    }//GEN-LAST:event_loansPageButtonActionPerformed

    private void spendingsPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spendingsPageButtonActionPerformed
        enablePage(4);
    }//GEN-LAST:event_spendingsPageButtonActionPerformed

    private void transactionsPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionsPageButtonActionPerformed
        getInfo("frame of reference", "transactions");
        enablePage(5);
    }//GEN-LAST:event_transactionsPageButtonActionPerformed

    private void trendsPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trendsPageButtonActionPerformed
        enablePage(6);
    }//GEN-LAST:event_trendsPageButtonActionPerformed

    private void tabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabbedPaneStateChanged

    }//GEN-LAST:event_tabbedPaneStateChanged

    private void accountsPageTitleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountsPageTitleButtonActionPerformed

    }//GEN-LAST:event_accountsPageTitleButtonActionPerformed

    private void budgetsPageTitleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_budgetsPageTitleButtonActionPerformed
        insertIntoBudgetsCombo();
        addBarGraph(getSpendings());
    }//GEN-LAST:event_budgetsPageTitleButtonActionPerformed

    private void loansPageTitleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loansPageTitleButtonActionPerformed
        loanPagePaymentSlider.enable();
        ArrayList<Loan> loans = new ArrayList<>();
        loans.add(new Loan(1000, "May 1 2020", "Centris", 3.4, 1, 500));
        inputLoanIntoLoanPage(loans);
    }//GEN-LAST:event_loansPageTitleButtonActionPerformed

    private void spendingsPageTitleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spendingsPageTitleButtonActionPerformed
        addRingChart();
    }//GEN-LAST:event_spendingsPageTitleButtonActionPerformed

    private void transactionsPageTitleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionsPageTitleButtonActionPerformed

    }//GEN-LAST:event_transactionsPageTitleButtonActionPerformed

    private void trendsPageTitleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trendsPageTitleButtonActionPerformed
        trendsPageGraphPanel.removeAll();
        addLineGraph();
    }//GEN-LAST:event_trendsPageTitleButtonActionPerformed

    private void budgetsPageComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_budgetsPageComboBoxActionPerformed
        String text = (String) budgetsPageComboBox.getSelectedItem();
        String[] split = text.split(", ");
        ArrayList<Spending> spendings = getSpendings();
        ArrayList<Spending> newSpendings = new ArrayList<>();
        for (Spending s : spendings) {
            if (s.getType().equals(split[0]) && s.getSDF().equals(split[1])) {
                newSpendings.add(s);
            }
        }
        addBarGraph(newSpendings);
    }//GEN-LAST:event_budgetsPageComboBoxActionPerformed

    private void loanPagePaymentSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_loanPagePaymentSliderStateChanged
        double loanAmt = Double.parseDouble(loanPageLoanAmountInfo.getText());
        int paymentAmt = loanPagePaymentSlider.getValue();
        loanPageHighPayment.setText(String.valueOf(loanAmt * paymentAmt / 100));
    }//GEN-LAST:event_loanPagePaymentSliderStateChanged

    public ArrayList<Spending> getSpendings() {
        ArrayList<Spending> spendings = new ArrayList<>();
        spendings.add(new Spending(600, "January 1 2020", "Utilities"));
        spendings.add(new Spending(500, "January 1 2020", "Car Bill"));
        spendings.add(new Spending(250, "January 1 2020", "Food"));
        spendings.add(new Spending(200, "January 1 2020", "Water Bill"));
        spendings.add(new Spending(400, "January 1 2020", "Gas"));
        spendings.add(new Spending(600, "January 2 2020", "Utilities"));
        spendings.add(new Spending(500, "January 2 2020", "Car Bill"));
        spendings.add(new Spending(250, "January 2 2020", "Food"));
        spendings.add(new Spending(200, "January 2 2020", "Water Bill"));
        spendings.add(new Spending(400, "January 2 2020", "Gas"));
        spendings.add(new Spending(600, "March 1 2020", "Utilities"));
        spendings.add(new Spending(500, "March 1 2020", "Car Bill"));
        spendings.add(new Spending(250, "March 1 2020", "Food"));
        spendings.add(new Spending(200, "March 1 2020", "Water Bill"));
        spendings.add(new Spending(400, "March 1 2020", "Gas"));
        spendings.add(new Spending(600, "April 1 2020", "Utilities"));
        spendings.add(new Spending(500, "April 1 2020", "Car Bill"));
        spendings.add(new Spending(250, "April 1 2020", "Food"));
        spendings.add(new Spending(200, "April 1 2020", "Water Bill"));
        spendings.add(new Spending(400, "April 1 2020", "Gas"));
        spendings.add(new Spending(600, "May 1 2020", "Utilities"));
        spendings.add(new Spending(500, "May 1 2020", "Car Bill"));
        spendings.add(new Spending(250, "May 1 2020", "Food"));
        spendings.add(new Spending(200, "May 1 2020", "Water Bill"));
        spendings.add(new Spending(400, "May 1 2020", "Gas"));
        return spendings;
    }

    public void insertIntoBudgetsCombo() {
        ArrayList<Spending> spendings = getSpendings();
        spendings.forEach((s) -> {
            budgetsPageComboBox.addItem(s.getType() + ", " + s.getSDF());
        });
    }

    public void addBarGraph(ArrayList<Spending> spendings) {
        budgetsPageGraphPanel.removeAll();
        DefaultCategoryDataset data = new DefaultCategoryDataset();
        spendings.forEach((Spending s) -> {
            data.addValue(s.getAmount(), s.getType(), s.getSDF());
        });
        JFreeChart chart = ChartFactory.createBarChart("Budgets Graph for " + spendings.get(0).getFrame(), "Type", "Amount", data);
        ChartPanel panel = new ChartPanel(chart);
        budgetsPageGraphPanel.add(panel);
    }

    public void addLineGraph() {
        ArrayList<Trend> trends = new ArrayList<>();
        trends.add(new Trend(100, "January 1 2020", "Food"));
        trends.add(new Trend(200, "January 1 2020", "Gas"));
        trends.add(new Trend(300, "January 1 2020", "Utilities"));
        trends.add(new Trend(400, "January 1 2020", "Grocery"));
        trends.add(new Trend(500, "January 1 2020", "Bills"));
        trends.add(new Trend(600, "January 1 2020", "Movies"));
        trends.add(new Trend(200, "May 1 2020", "Food"));
        trends.add(new Trend(300, "May 1 2020", "Gas"));
        trends.add(new Trend(400, "May 1 2020", "Utilities"));
        trends.add(new Trend(500, "May 1 2020", "Grocery"));
        trends.add(new Trend(600, "May 1 2020", "Bills"));
        trends.add(new Trend(700, "May 1 2020", "Movies"));
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        trends.forEach((t) -> {
            dataset.addValue(t.getAmount(), t.getType(), t.getSDF());
        });
        JFreeChart chart = ChartFactory.createLineChart("Trends Graph", "Frame", "Type", dataset);
        ChartPanel panel = new ChartPanel(chart);
        trendsPageGraphPanel.add(panel);
    }

    public void addPieChart() {
        ArrayList<Budget> budgets = new ArrayList<>();
        budgets.add(new Budget(200, "May 1 2020", 150, "Food"));
        budgets.add(new Budget(300, "May 1 2020", 150, "Gas"));
        DefaultCategoryDataset source = new DefaultCategoryDataset();
        budgets.forEach((b) -> {
            source.addValue(b.getPaid(), b.getSDF(), b.getType());
        });
        PieDataset dataset = new CategoryToPieDataset(source, TableOrder.BY_ROW, 0);
        JFreeChart chart = ChartFactory.createPieChart("Budget Graph for " + budgets.get(0).getSDF(), dataset);
        chart.removeLegend();
        ChartPanel panel = new ChartPanel(chart);
        spendingsPageGraphPanel.add(panel);
    }

    public void addRingChart() {
        ArrayList<Budget> budgets = new ArrayList<>();
        budgets.add(new Budget(200, "May 1 2020", 150, "Food"));
        budgets.add(new Budget(50, "May 1 2020", 50, "Remaining"));
        DefaultCategoryDataset source = new DefaultCategoryDataset();
        budgets.forEach((b) -> {
            source.addValue(b.getPaid(), b.getSDF(), b.getType());
        });
        PieDataset dataset = new CategoryToPieDataset(source, TableOrder.BY_ROW, 0);
        JFreeChart chart = ChartFactory.createRingChart("Budget Graph for " + budgets.get(0).getSDF(), dataset, false, false, Locale.US);
        chart.removeLegend();
        ChartPanel panel = new ChartPanel(chart);
        spendingsPageGraphPanel.add(panel);
    }
    
    public void inputLoanIntoLoanPage(ArrayList<Loan> loans){
        loanPageLoanAmountInfo.setText(String.valueOf(loans.get(0).getAmount()));
        loanPageLoanInstitutionInfo.setText(String.valueOf(loans.get(0).getInstitution()));
        loanPageLoanInfo.setText(String.valueOf(loans.get(0).getSDF()));
    }

    public ArrayList<JButton> getButtons() {
        return buttons;
    }

    /**
     * Function to prompt the user to get the information they are seeking
     *
     * @param obj the type of object they want (frame of reference, type,
     * institution, etc.)
     * @param desInfo the type of that object they want (account, budget, loan,
     * etc.)
     * @return the string the user entered into the prompt
     */
    public String getInfo(String obj, String desInfo) {
        return JOptionPane.showInputDialog("Please enter the " + obj + " you seek for your " + desInfo + ":");
    }

    public int getTabSelected() {
        return tabbedPane.getSelectedIndex();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinancialPortalFrameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinancialPortalFrameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinancialPortalFrameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinancialPortalFrameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FinancialPortalFrameView().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem accountsPageButton;
    private javax.swing.JPanel accountsPagePanel;
    private javax.swing.JLabel accountsPagePanelTitle;
    private javax.swing.JButton accountsPageTitleButton;
    private javax.swing.JPanel accountsPageTitlePanel;
    private javax.swing.JMenuItem budgetsPageButton;
    private javax.swing.JComboBox<String> budgetsPageComboBox;
    private javax.swing.JPanel budgetsPageGraphPanel;
    private javax.swing.JPanel budgetsPagePanel;
    private javax.swing.JLabel budgetsPageTitle;
    private javax.swing.JButton budgetsPageTitleButton;
    private javax.swing.JPanel budgetsPageTitlePanel;
    private javax.swing.JMenu fileButton;
    private javax.swing.JMenuItem homePageButton;
    private javax.swing.JPanel homePagePanel;
    private javax.swing.JTextArea homePageTextArea;
    private javax.swing.JLabel homePageTitle;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea10;
    private javax.swing.JTextArea jTextArea11;
    private javax.swing.JTextArea jTextArea12;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextArea jTextArea9;
    private javax.swing.JLabel loanPageHighPayment;
    private javax.swing.JLabel loanPageLoanAmountInfo;
    private javax.swing.JLabel loanPageLoanInfo;
    private javax.swing.JLabel loanPageLoanInstitutionInfo;
    private javax.swing.JLabel loanPageLowPayment;
    private javax.swing.JSlider loanPagePaymentSlider;
    private javax.swing.JMenuItem loansPageButton;
    private javax.swing.JPanel loansPagePanel;
    private javax.swing.JPanel loansPageTablePanel;
    private javax.swing.JLabel loansPageTitle;
    private javax.swing.JButton loansPageTitleButton;
    private javax.swing.JPanel loansPageTitlePanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu pagesButton;
    private javax.swing.JMenuItem quitButton;
    private javax.swing.JMenuItem spendingsPageButton;
    private javax.swing.JPanel spendingsPageGraphPanel;
    private javax.swing.JPanel spendingsPagePanel;
    private javax.swing.JLabel spendingsPageTitle;
    private javax.swing.JButton spendingsPageTitleButton;
    private javax.swing.JPanel spendingsPageTitlePanel;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JMenuItem transactionsPageButton;
    private javax.swing.JPanel transactionsPagePanel;
    private javax.swing.JLabel transactionsPageTitle;
    private javax.swing.JButton transactionsPageTitleButton;
    private javax.swing.JPanel transactionsPageTitlePanel;
    private javax.swing.JMenuItem trendsPageButton;
    private javax.swing.JPanel trendsPageGraphPanel;
    private javax.swing.JPanel trendsPagePanel;
    private javax.swing.JLabel trendsPageTitle;
    private javax.swing.JButton trendsPageTitleButton;
    private javax.swing.JPanel trendsPageTitlePanel;
    // End of variables declaration//GEN-END:variables
}
